plugin/git: fix errors inside bare repo
frmendes/geometry pull request #130
Opened 2017-03-05 14:36 UTC by FildasPA

Hi there!

Sometimes you need to go into a bare repository, and then you get an error:

![error](https://cloud.githubusercontent.com/assets/12859895/23587999/9dee4aa6-01b6-11e7-9818-1b3c8b696237.png)

As you see, the git plugin is executing commands that it should not run here.

I tried to fix that. Now it displays a symbol instead, indicating you're in a bare repo:

![fixed](https://cloud.githubusercontent.com/assets/12859895/23588004/a9c68ce4-01b6-11e7-83cd-642182ff44b9.png)

Color & symbol can be set by the user.

Please tell me if you have any suggestions :)

2017-03-05 14:39 UTC, frm requested changes
It looks pretty good! Thanks! Just that one comment.

2017-03-05 14:39 UTC, frmendes commented on plugins/git/plugin.zsh
> +  if [[ $(command git rev-parse --is-inside-work-tree 2>/dev/null) != "true" ]] ; then
A bit of nitpicking but this `!= "true"` is kind of itching me. According to the docs, it returns `"false"` otherwise. Can we test for that?

2017-03-05 14:57 UTC, FildasPA commented on plugins/git/plugin.zsh
> +  if [[ $(command git rev-parse --is-inside-work-tree 2>/dev/null) != "true" ]] ; then
Is it okay like this?

2017-03-05 16:44 UTC, FildasPA commented
Is it suitable like this?

2017-03-06 15:49 UTC, frm approved these changes
I was using this for the day. Seems to be good. Thanks!

2017-03-06 15:49 UTC, merged