Support plugin pinning with built-in plugins
frmendes/geometry pull request #132
Opened 2017-03-14 03:14 UTC by desyncr

- Support plugin pinning for custom and builtin plugins
- Moved pinning logic to register method

The way a built-in plugin self-register as pinning is by calling `geometry_plugin_register +plugin-name`.

2017-03-14 22:46 UTC, frm requested changes
Looks great! But isn't the commit message wrong? Shouldn't it be "custom plugins"?

2017-03-15 04:47 UTC, jedahan requested changes
I think there is a way to get rid of the _GEOMETRY_PROMPT_PLUGINS_PINNED array completely, simplifying the code a bit.

2017-03-15 04:47 UTC, jedahan commented on lib/plugin.zsh
>    fi
Won't this always return false for pinned plugins? Here we check against `+plugin` but only ever register `plugin` in `_GEOMETRY_PROMPT_PLUGINS`

2017-03-15 05:05 UTC, jedahan commented
So the ergonomics for someone to pin a custom plugin, with this patchset:

```zsh
source $HOME/.zpm-init.zsh || {
  zpm frmendes/geometry
  zpm jedahan/geometry-hydrate
  exec zsh
}
geometry_plugin_unregister hydrate
geometry_plugin_register +hydrate
```

I could remove the unregister requirement from geometry-hydrate, but this would make it diverge more from main plugins because all the main plugins self register.

2017-03-15 11:44 UTC, desyncr commented
@jedahan The proposed approach gives the power to decide to be pinned or not to the plugins themselves. In this way, if you want `geometry-hydrate` plugin to be always pinned, you'll need to adapt the plugin to register this way:

     geometry_plugin_register +hydrate

If you think this plugin may either be pinned or not this plugin should support a configuration variable, also implemented by the plugin.

What do you think about this approach? Given you developed the pinning functionality you have a better idea of what should and should not go into it.

2017-03-15 12:32 UTC, desyncr commented
I believe your approach in #133 is more complete that this one. Let's move onto that!

2017-03-15 12:32 UTC, closed without merging