Simplify plugin pinning
frmendes/geometry pull request #133
Opened 2017-03-15 05:28 UTC by jedahan

Instead of keeping a separate array around, we just check
if a plugin is pinned in GEOMETRY_PROMPT_PLUGINS.

This allows third party plugins to be sourced anywhere,
registered when they want, and runtime check for pins.

This also makes it easier to runtime (un)pin.

Fixes #131 and #132

2017-03-15 23:04 UTC, frm requested changes
Well, :clap: :clap: :clap: for simplifying this to a single array.

As for runtime pinning/unpinning it can be useful. I don't see why not even though I haven't felt this need myself. This usually makes me reconsider whether we need it, but the increase in complexity isn't that much, it's not a bad trade-off.

However, I'd at least add a note for unaware users that the pinning is limited to the current session. Once that goes off, default settings get re-applied.

2017-03-15 23:04 UTC, frmendes commented on lib/plugin.zsh
> +    echo "Error: Missing argument."
Can you change this for something like "Missing the plugin name"? Just to be a tad bit more clear for when users experiment with this.

2017-03-15 23:04 UTC, frmendes commented on lib/plugin.zsh
> +    echo "Error: Missing argument."
Same as previous comment.

2017-03-15 23:54 UTC, jedahan commented
@frmendes I would rather not commit geometry_plugin_pin/geometry_plugin_unpin.  I would much rather keep things simple, like you said, especially since the temporary part would require people to have a weird workaround like `[[ $PROMPT_GEOMETRY_PLUGINS ]] || export PROMPT_GEOMETRY_PLUGINS=(git exec_time +rustup)` I just saw it in the TODO for the previous pull request.

2017-03-16 09:34 UTC, frmendes commented
@jedahan precisely that. I haven't felt the need to add those functions but they **can** be useful. Are they, though? The increase in complexity is not too big in this case since it's just a couple of `if`s although it may come back to bite us if we ever decide to change the actual plugin implementation.

that first commit, though ❤️

2017-03-18 14:58 UTC, jedahan commented
It seems we are in agreement regarding the first commit, mind if I close this PR and push it?

2017-03-18 15:19 UTC, frm approved these changes
Go right on ahead and merge it.

2017-03-18 15:30 UTC, merged