Initial background-jobs plugin implementation
frmendes/geometry pull request #135
Opened 2017-03-16 01:56 UTC by desyncr

Bare bones background-jobs plugin. No icon, color or configuration available. All suggestions welcome.

It will display as follows if there is one or more background jobs:

![screenshot from 2017-03-15 22-54-10](https://cloud.githubusercontent.com/assets/1857707/23978349/3c3217e0-09fc-11e7-96a8-9921b82e5eba.png)

It won't display anything if there is no background job.

2017-03-16 05:25 UTC, jedahan approved these changes
Looks like a solid start to me.

2017-03-16 05:25 UTC, jedahan commented on plugins/jobs/plugin.zsh
> +  return true
I like true/false better than 0/1, we should start using this convention in more places

2017-03-16 05:25 UTC, jedahan commented on plugins/jobs/plugin.zsh
> +}
this is unnecessary - if the check function is not defined, it defaults to return true. If you like it for consistency or as an example its fine to keep.

2017-03-16 09:27 UTC, frm requested changes
I like it but I'd rather have some colors and configurations already set up. It's not that much of a hassle that would justify an incremental build since you'd basically only need to add a color variable and a symbol variable or something like that.

2017-03-16 09:27 UTC, frmendes commented on plugins/jobs/plugin.zsh
> +}
TIL

2017-03-16 09:27 UTC, frmendes commented on plugins/jobs/plugin.zsh
> +  return true
I agree. There are a number of rules we are starting to define that maybe would justify a small `CONTRIBUTING.md` file. What do you think?

2017-03-16 17:29 UTC, jedahan commented on plugins/jobs/plugin.zsh
> +  return true
splitting out the readme into user-focused, and contributing to dev-focused information seems good to me.

2017-03-16 17:52 UTC, desyncr commented on plugins/jobs/plugin.zsh
> +  return true
Agreed. Gonna create an issue to keep track of it.

2017-03-16 17:53 UTC, desyncr commented on plugins/jobs/plugin.zsh
> +}
Yep, I wasn't sure about it so I left it after some debugging.

2017-03-16 17:54 UTC, desyncr commented
Gonna add color, symbol and if I can also a format string.

2017-04-04 17:12 UTC, desyncr commented
Sorry for the delay. Gonna give it a second iteration tonight. :)

2017-04-07 01:50 UTC, desyncr commented
![screenshot from 2017-04-06 22-49-36](https://cloud.githubusercontent.com/assets/1857707/24782259/65138d4e-1b1b-11e7-94c0-332ea13e8ce0.png)

2017-04-10 14:10 UTC, desyncr commented
@frmendes Should be done now!

2017-04-17 09:09 UTC, fribmendes commented
Sorry, Easter is a bit of a hassle here in Portugal. I'll get back to this shortly.

2017-04-17 12:31 UTC, desyncr commented
No problem!

2017-04-20 10:36 UTC, frm approved these changes

2017-04-20 12:43 UTC, merged

2017-04-20 12:43 UTC, desyncr commented
It's done!