Fix malicious branch name shell injection
frmendes/geometry pull request #138
Opened 2017-03-18 15:28 UTC by jedahan

Described in https://github.com/njhartwell/pw3nage

If a branch name has something like `$(./pw3nage)`
we would execute it. Now we escape the $ symbol.

Fixes #137

2017-03-18 15:30 UTC, frm requested changes
I was messing around with this yesterday and this solution doesn't cover cases where the branch name is ./pw3n with backticks surrounding

2017-03-18 15:55 UTC, jedahan commented
Yeah its a trickier problem than I thought.

So we want to disable shell expansion for the second parameter until the time it is actually rendered in the prompt. I will have to take a break and think about it more. If you come up with a good solution feel free to take it over.

2017-03-18 16:03 UTC, frmendes commented
Well, your solution is pretty much the same I had. I found it trickier to replace the backticks, so I just said "I'll think about it tomorrow". And here we are. I'll let you know if I come up with something.

2017-03-18 16:03 UTC, frmendes commented
Also, I'd prefer to avoid fixes like the one presented in https://github.com/njhartwell/pw3nage/pull/2 where all non-whitelisted characters are replaced with a `-`.

2017-04-05 04:33 UTC, jedahan commented
Closing in favour of #142

2017-04-05 04:33 UTC, closed without merging