Add changelog and tag v1.0.0
frmendes/geometry pull request #146
Opened 2017-04-05 21:47 UTC by frmendes

The project seems mature enough to mark it as `v1.0.0` but I'd actually prefer feedback on this.

I took the liberty of using semver and adding the [Keep A Changelog](http://keepachangelog.com/en/0.3.0/) format changelog.

After merging, I'll create the release draft and we can take it from there.

2017-04-05 21:48 UTC, frmendes commented
It also fixes #121

2017-04-05 22:23 UTC, desyncr commented
I also believe `1.0.0` is a good starting point. Project is quite stable right now and won't face huge changes in the short term.

2017-04-06 16:20 UTC, desyncr approved these changes
I haven't used `Unreleased` section before but I have no issues against it, seems reasonable.

2017-04-06 16:22 UTC, desyncr commented
After @jedahan OK I think we should merge it and release right away. No need to wait for pending issues/PR.

What you think @frmendes?

2017-04-06 17:16 UTC, jedahan requested changes
Good context, just want to add one link then we can push

2017-04-06 17:16 UTC, jedahan commented on CHANGELOG.md
> +## 1.0.0 - 2017-04-05
maybe we want to link to the current revision here?

2017-04-06 17:17 UTC, jedahan commented on CHANGELOG.md
> +## 1.0.0 - 2017-04-05
Or is that impossible because we have not pushed it yet?

2017-04-07 14:02 UTC, frmendes commented on CHANGELOG.md
> +## 1.0.0 - 2017-04-05
We have not pushed it yet. I could probably link to the revision and guess the correct URL. However, [Keep A Changelog](http://keepachangelog.com/en/0.3.0/) suggests linking the comparison between 2 consecutive versions.

2017-04-07 14:04 UTC, frmendes commented
@desyncr 

> I haven't used `Unreleased` section before but I have no issues against it, seems reasonable.

I haven't either but I'm willing to give it a shot and try that format. If you have any suggestions I'd love to hear them!

> I think we should merge it and release right away. No need to wait for pending issues/PR.

I agree 😄 as soon as @jedahan approves it, I'm releasing. Should I just make a release draft or can I release it right away as "Initial release"?

2017-04-07 15:34 UTC, jedahan approved these changes

2017-04-07 15:40 UTC, jedahan commented
Initial release is good. I wonder if we should do a little coordinated marketing around the release. Posting screenshots on r/unixporn, twitter, etc...

2017-04-10 13:33 UTC, frmendes commented
I agree with the marketing. Do you want to talk about this in an issue or gitter? @jedahan @desyncr

2017-04-10 13:34 UTC, merged

2017-04-10 14:53 UTC, desyncr commented
We should probably hang out on gitter to talk about it (there will be too much back and forward). We should set a date/time we can all hang out a couple of minutes.

2017-04-13 10:03 UTC, fribmendes commented
@desyncr [Sure, sounds great!](https://youtu.be/GLbzN1Q1Agw?t=34s)

cc @jedahan

2017-04-13 23:13 UTC, jedahan commented
I am actually on vacation out of my normal country so it is a bit difficult for me to communicate but I will try. On April 19 I will be more reliable.