Add a note about setting var. when using antigen
frmendes/geometry pull request #172
Opened 2017-06-21 15:47 UTC by zapashcanon

Hi,

Something like:

```sh
. /usr/share/zsh-antigen/antigen.zsh

GEOMETRY_SYMBOL_PROMPT="λ"

antigen use oh-my-zsh
antigen theme frmendes/geometry
```

won't work. But:

```sh
GEOMETRY_SYMBOL_PROMPT="λ"

. /usr/share/zsh-antigen/antigen.zsh

antigen use oh-my-zsh
antigen theme frmendes/geometry
```

is ok. So, I just added a note about it.

2017-06-21 16:35 UTC, fribmendes commented
Hi!

Thanks for this. Before merging, are you sure this just applies to antigen? Wouldn't it be similar in `zplug` (iirc)?

2017-06-21 17:32 UTC, zapashcanon commented
I don't use/know zplug, so can't help here, sorry !

2017-06-21 19:43 UTC, desyncr commented
It may be too specific to the plugin manager but I don't see too much of a trouble with adding it. 👍

2017-06-21 20:53 UTC, fribmendes commented
Oh, yeah, I'm up for merging! I was just wondering if we should change it to be broader, without even specifying a package manager. As an example: "(...) you should set them before loading the theme in your package manager (e.g. antigen)"

2017-06-21 22:15 UTC, desyncr commented
Agree on that point.

2017-06-22 09:24 UTC, zapashcanon commented
The fact is that it's not just about loading the theme in the package manager. In my first example, I kinda set them before loading the theme with the package manager but it doesn't work.

2017-06-22 15:02 UTC, desyncr commented
@zapashcanon Can you clarify what works and what doesn't work?

I'm up for merging but text needs to be reworked in a generic way (example above is OK).

2017-06-22 17:41 UTC, zapashcanon commented
It very clear in my first post, no ?

You must set env. var. before loading antigen. Loading them before `antigen theme frmendes/geometry` is not enough.

2017-06-22 17:50 UTC, desyncr commented
@zapashcanon What wasn't clear was your previous comment. Otherwise I wouldn't ask.

2017-06-22 18:09 UTC, zapashcanon commented
Hum ok. It was just another way to explain what's in the first post.

2017-07-07 21:16 UTC, fribmendes commented
Any updates on this?

2017-07-07 23:31 UTC, desyncr requested changes
Re word in a non plugin specific way: "(...) you should set them before loading the theme in your package manager (e.g. antigen)"

2017-07-10 14:32 UTC, zapashcanon commented
It's not really about setting them before loading the theme. (This is already in the `README`).

It's about setting them before "loading" the package manager. Sourcing `antigen.zsh` for antigen e.g., but I don't know how other package manager are loaded/work, so it may not be the case.

2017-08-09 14:49 UTC, frm approved these changes
We can merge this, I think. It's really a matter of semantics and if the issue arises in other package managers, we can update it.

Sorry for taking so long to reply @zapashcanon. Tough couple of months.

2017-08-09 14:50 UTC, desyncr commented
@zapashcanon This seems to be an issue with this particular package manager rather than with geometry itself.

We think geometry should be agnostic to a package manager. It adds various install methods in its `README.md` but just as a convenience.

2017-08-09 14:54 UTC, fribmendes commented
@desyncr yeah, but if it affects users we might as well add in that information. It's not a big deal and it can avoid issues in the future for anyone who tries to install it.

Although I just noticed it's kinda lost in the middle of the `README`. I'd rephrase it and put it in the `antigen` specific section. What do you think?

2017-10-19 21:32 UTC, fribmendes commented
@zapashcanon can you take a look at my last comment?

2017-11-17 23:58 UTC, desyncr commented
@fribmendes @zapashcanon The issue with Antigen is resolved so this gotcha is not necessary anymore.

2017-11-22 11:30 UTC, fribmendes commented
Should we close this then? @desyncr

2017-11-22 12:01 UTC, desyncr commented
Yes. Thanks @zapashcanon for the work. It's currently solved in Antigen itself.

2017-11-22 12:01 UTC, closed without merging