Show human-readable timestamp for long-running commands
frmendes/geometry pull request #22
Opened 2016-10-17 19:40 UTC by jedahan

Second try of #21.

There is a weird coloring issue - maybe we should have different colors for git time vs long running time

long running -> white -> yellow -> red
git time -> green -> white -> red

2016-10-21 11:07 UTC, frmendes commented on geometry.zsh
> +PROMPT_GEOMETRY_EXEC_TIME=${PROMPT_GEOMETRY_EXEC_TIME:-true}
Can we default this to false? It feels like this would be added for users that have longer running commands, a subset of the overall users.

2016-10-21 11:08 UTC, frmendes commented on geometry.zsh
> -  RPROMPT="$(prompt_geometry_virtualenv)$(prompt_geometry_git_info)%f"
Won't this remove the `virtualenv` support?

2016-10-21 11:09 UTC, frmendes commented
Git time is supposed to be green -> white/yellow -> red. I don't have any particular opinion on the colors for the long running commands. Not sure if I understood the issue.

2016-10-23 16:54 UTC, jedahan commented on geometry.zsh
> -  RPROMPT="$(prompt_geometry_virtualenv)$(prompt_geometry_git_info)%f"
Fixed, good catch on the mistake.

2016-10-23 16:55 UTC, jedahan commented on geometry.zsh
> +PROMPT_GEOMETRY_EXEC_TIME=${PROMPT_GEOMETRY_EXEC_TIME:-true}
Defaulted to false now

2016-10-23 16:57 UTC, jedahan commented
The color thing is a non-issue, I was just thinking about it weird

2016-10-23 16:59 UTC, frm requested changes

2016-10-23 16:59 UTC, frmendes commented on README.md
> +by setting the `PROMPT_GEOMETRY_EXEC_TIME` variable to false.
This already defaults to false, now. Just this final update before merging.

2016-10-23 17:05 UTC, jedahan commented
Now this is super weird, I am getting "normal" as the string display for time elapsed. gonna see what the deal is.

2016-10-23 17:18 UTC, jedahan commented
OK fixed a few bugs: the :: separator not working as described, and the actual display. Should be ready to merge now

2016-10-23 22:09 UTC, frm approved these changes

2016-10-23 22:10 UTC, merged

2016-10-23 22:10 UTC, frmendes commented
Just merged! Thanks again!