Initial async git prompt implementation
frmendes/geometry pull request #26
Opened 2016-11-03 04:15 UTC by desyncr

Code based off
http://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/

Fixes https://github.com/frmendes/geometry/issues/6

2016-11-07 10:09 UTC, frmendes commented
I'm assuming you'll add more to this PR or is the TODO supposed to be added as an ongoing process among different PRs?

2016-11-07 12:16 UTC, desyncr commented
I'll add them to this PR and I created the TODO as to receive feedback on the items before start to work on them, if necessary.

2016-11-09 02:49 UTC, desyncr commented
Done. Accepting feedback.

2016-11-13 23:14 UTC, frm requested changes
Looks pretty good and clean! Tested a bit and it's much better.

Just the typo thing and that one question. I can't merge since there are conflicts as well.

2016-11-13 23:14 UTC, frmendes commented on geometry.zsh
> +GEOMETRY_ASYNC_PROMPT_TMP_FILENAME=${GEOMETRY_ASYNC_PROMPT_TMP_FILENAME:-/tmp/geometry-promp-git-info-}
Can you fix the typo? `promp` should be `prompt`. Also, why the final `-`?

2016-11-13 23:14 UTC, frmendes commented on geometry.zsh
> +    function precmd() {
`precmd` runs before each prompt, but does it interfere with other `precmd` hook functions?

2016-11-14 01:54 UTC, desyncr commented on geometry.zsh
> +GEOMETRY_ASYNC_PROMPT_TMP_FILENAME=${GEOMETRY_ASYNC_PROMPT_TMP_FILENAME:-/tmp/geometry-promp-git-info-}
Sure thing. The trailing dash is just for file name formatting: `/tmp/geometry-prompt-git-info-1234` where `1234` is the process id.

2016-11-14 02:08 UTC, desyncr commented on geometry.zsh
> +    function precmd() {
It doesn't look like it interferes at all. Nevertheless I'm gonna change to use preferred format `add-zsh-hook`.

2016-11-14 02:32 UTC, desyncr commented
Done. Fixed typo and replaced `precmd` function for `add-zsh-hook`.

Squashed and fixed merge issue.

2016-11-14 09:17 UTC, frm approved these changes

2016-11-14 09:17 UTC, merged