Update README
frmendes/geometry pull request #53
Opened 2016-12-09 22:38 UTC by frmendes

Update the README with information about new architecture, features and missing screenshots.

There's a generic README on the root of the project, one on the plugins directory, detailing how plugins work and finally one per plugin.

Feel free to make corrections @desyncr

2016-12-09 22:51 UTC, desyncr commented
Looks good. I'm take a closer look and if everything is OK I'm gonna squash everything and put it live!

2016-12-09 22:52 UTC, frmendes commented
Please do. I probably missed something. Long day.

2016-12-09 23:34 UTC, desyncr requested changes
There are a few things to check out. Overall a great work!

2016-12-09 23:34 UTC, desyncr commented on README.md
> +geometry has an internal plugin architecture. The default plugins are `exec_time` and `git`. But you can also enable a number of them just by setting the `GEOMETRY_PROMPT_PLUGINS` variable in your ow
The variable for built-in plugins is `GEOMETRY_PROMPT_DEFAULT_PROMPTS`, which, looking at it now, is a terrible name.

This is different from `GEOMETRY_PROMPT_PLUGINS` due that in the setup phrase we source plugins from listed in `GEOMETRY_PROMPT_DEFAULT_PROMPTS`; we use `GEOMETRY_PROMPT_PLUGINS` to keep track of registered plugins.

I guess we should rename `GEOMETRY_PROMPT_DEFAULT_PROMPTS` to `GEOMETRY_PROMPT_PLUGINS` and `GEOMETRY_PROMPT_PLUGINS` to `_GEOMETRY_PROMPT_PLUGINS` as it's actually a sort of private variable.

2016-12-09 23:34 UTC, desyncr commented on README.md
> +GEOMETRY_PROMPT_PLUGINS=(virtualenv dockermachine)
`dockermachine` plugin is actually `docker_machine`.

2016-12-09 23:34 UTC, desyncr commented on plugins/README.md
> +Let's assume you want to add a plugin that prints `(☞ﾟ∀ﾟ)☞` when the git branch
Is this plugin available? I actually want it :-D

2016-12-09 23:36 UTC, desyncr commented on README.md
> +geometry has an internal plugin architecture. The default plugins are `exec_time` and `git`. But you can also enable a number of them just by setting the `GEOMETRY_PROMPT_PLUGINS` variable in your ow
I'm gonna take a look at this [here](https://github.com/frmendes/geometry/issues/55).

2016-12-10 00:07 UTC, desyncr requested changes
A few more small things to look for.

2016-12-10 00:07 UTC, desyncr commented on plugins/README.md
> +GEOMETRY_PROMPT_PLUGINS=(virtualenv dockermachine)
As this variable is not defined until geometry is loaded, it's empty as this time, so we can't _add_ plugins to the defaults, but _define_ the defaults. So as an example I'd put:

    GEOMETRY_PROMPT_PLUGINS=(virtualenv docker_machine exec_time git)

So we make it clear, and I'll change the above paragraph for the following: 

    By default, geometry uses `git` and `exec_time`. You can configure a different setup by changing the `GEOMETRY_PROMPT_PLUGINS` variable in your own configuration files.

2016-12-10 00:07 UTC, desyncr commented on plugins/README.md
> +is clean and `(ノಠ益ಠ)ノ彡┻━┻` when it's dirty. Well call it `pretty_git`.
"Well call it `pretty_git`." -> "Let's call it `pretty_git`."

2016-12-10 00:07 UTC, desyncr commented on plugins/docker_machine/README.md
> +environment variable. Defaults to `⚓.
There is an unclosed backtick.

2016-12-10 00:11 UTC, desyncr commented
Most things in review are small things, let me know if you want me to go ahead and fix them up. Once #55 is merged we can move on and get it live!

2016-12-10 03:23 UTC, merged